2024-02-27 13:26:36,846 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022F27A46250>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:26:37,047 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022F27A46950>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:26:37,448 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022F27A47210>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:26:38,249 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022F27A47AD0>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:26:39,850 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022F27A68390>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:26:39,850 - ERROR - Error al realizar la solicitud a https://proxy-daily.com: HTTPSConnectionPool(host='proxy-daily.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022F27A68C10>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)"))
2024-02-27 13:26:39,852 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022F27A69C10>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:26:40,054 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022F27A6A490>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:26:40,455 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022F27A6AD50>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:26:41,256 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022F27A6B610>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:26:42,857 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022F27A6BED0>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:26:43,012 - ERROR - Error al realizar la solicitud a https://proxy-daily.com: HTTPSConnectionPool(host='proxy-daily.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022F27A7C790>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)"))
2024-02-27 13:26:43,012 - INFO - Fin del programa
2024-02-27 13:26:43,021 - INFO - Duplicados eliminados. Resultado guardado en http.txt
2024-02-27 13:26:44,741 - INFO - Archivo http_proxies.txt eliminado.
2024-02-27 13:26:44,742 - INFO - Archivo http.txt renombrado a http_proxies.txt.
2024-02-27 13:26:44,742 - INFO - Commit y push completados.
2024-02-27 13:27:45,677 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CDC5AEA10>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:27:45,878 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CDCBF6950>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:27:46,279 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CDCBF7210>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:27:47,080 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CDCBF7AD0>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:27:48,681 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CDCC18390>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:27:48,681 - ERROR - Error al realizar la solicitud a https://proxy-daily.com: HTTPSConnectionPool(host='proxy-daily.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CDCC18C10>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)"))
2024-02-27 13:27:48,683 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CDCC19C10>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:27:48,884 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CDCC1A490>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:27:49,284 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CDCC1AD50>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:27:50,085 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CDCC1B610>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:27:51,687 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CDCC1BED0>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:27:51,793 - ERROR - Error al realizar la solicitud a https://proxy-daily.com: HTTPSConnectionPool(host='proxy-daily.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000014CDCC2C790>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)"))
2024-02-27 13:27:51,793 - INFO - Fin del programa
2024-02-27 13:27:51,800 - INFO - Duplicados eliminados. Resultado guardado en http.txt
2024-02-27 13:27:52,967 - INFO - Archivo http_proxies.txt eliminado.
2024-02-27 13:27:52,968 - INFO - Archivo http.txt renombrado a http_proxies.txt.
2024-02-27 13:27:52,968 - INFO - Commit y push completados.
2024-02-27 13:28:17,271 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027111B4EA10>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:28:17,472 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027112206950>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:28:17,873 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027112207210>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:28:18,674 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027112207AD0>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:28:20,275 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027112228390>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:28:20,275 - ERROR - Error al realizar la solicitud a https://proxy-daily.com: HTTPSConnectionPool(host='proxy-daily.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027112228C10>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)"))
2024-02-27 13:28:20,277 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000027112229C10>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:28:20,478 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002711222A490>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:28:20,880 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002711222AD50>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:28:21,680 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002711222B610>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:28:23,391 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002711222BED0>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:28:23,391 - ERROR - Error al realizar la solicitud a https://proxy-daily.com: HTTPSConnectionPool(host='proxy-daily.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002711223C790>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)"))
2024-02-27 13:28:23,391 - INFO - Fin del programa
2024-02-27 13:28:23,398 - INFO - Duplicados eliminados. Resultado guardado en http.txt
2024-02-27 13:28:24,527 - INFO - Archivo http_proxies.txt eliminado.
2024-02-27 13:28:24,528 - INFO - Archivo http.txt renombrado a http_proxies.txt.
2024-02-27 13:28:24,528 - INFO - Commit y push completados.
2024-02-27 13:28:58,768 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002A6D322EA10>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:28:58,970 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002A6D38E6950>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:28:59,371 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002A6D38E7210>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:29:00,171 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002A6D38E7AD0>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:29:01,772 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002A6D3908390>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:29:01,772 - ERROR - Error al realizar la solicitud a https://proxy-daily.com: HTTPSConnectionPool(host='proxy-daily.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002A6D3908C10>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)"))
2024-02-27 13:29:01,773 - WARNING - Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002A6D3909C10>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:29:01,975 - WARNING - Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002A6D390A490>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:29:02,376 - WARNING - Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002A6D390AD50>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:29:03,177 - WARNING - Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002A6D390B610>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:29:04,778 - WARNING - Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002A6D390BED0>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)")': /
2024-02-27 13:29:04,916 - ERROR - Error al realizar la solicitud a https://proxy-daily.com: HTTPSConnectionPool(host='proxy-daily.com', port=443): Max retries exceeded with url: / (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x000002A6D391C790>: Failed to resolve 'proxy-daily.com' ([Errno 11002] getaddrinfo failed)"))
2024-02-27 13:29:04,916 - INFO - Fin del programa
2024-02-27 13:29:04,922 - INFO - Duplicados eliminados. Resultado guardado en http.txt
2024-02-27 13:29:06,042 - INFO - Archivo http_proxies.txt eliminado.
2024-02-27 13:29:06,043 - INFO - Archivo http.txt renombrado a http_proxies.txt.
2024-02-27 13:29:06,043 - INFO - Commit y push completados.
